name: Ruby Tests

env:
  TZ: Europe/London

on:
  push:
  pull_request:

jobs:
  test:
    name: Rspec
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [ "3.1", "3.2", "3.3", "3.4", "4.0", head ]
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run rspec
        run: bundle exec rspec

      - name: Upload coverage reports to Codecov
        uses: sanger/.github/.github/actions/tests/codecov@master
        with:
          name: ${{ github.run_id }}_${{ github.job }}_${{ github.event_name }}_${{ matrix.ruby }}
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ github.event_name }}
          disable-search: true
          files: ${{ github.workspace }}/lcov.info
